### PR TITLE
Extension of GH Action to update page branch

### PR DESCRIPTION
**Pull request by lechnerc77**
As discussed via email, I have updated the action for the update of the video galley to take into account the `pages` branch and update the corresponding markdown file there. 

This PR contains the adjustment for both actions (myNewsWrap and SAPOnAzure)

### CODE REVIEW

**Comment by MartinPankraz** [comment]
@lechnerc77: the change on md level worked but of course the site was not rebuilt. Chaining both workflows or adding the jekyll build to your action?

KR
Martin

**Comment by lechnerc77** [comment]
@MartinPankraz would it also be an option to add as event the "commit" to the action in the pages-branch? Or is there a side-effect I am not aware of?

**Comment by MartinPankraz** [comment]
@lechnerc77 worth a try. Not aware of any problems yet.

**Comment by MartinPankraz** [comment]
@lechnerc77 reverted the change and made the videos inline. If the YouTube playlist is sorted by date it would show the latest automatically. Otherwise I made a note on choosing the playlist button.

**Comment by lechnerc77** [comment]
Looks good and makes sense for the gallery

**Comment by MartinPankraz** [comment]
@lechnerc77 could you sort your youtube playlist by date, so that the latest one comes first, rather the first one? Holger switched sorting and that did the trick right away.

**Comment by lechnerc77** [comment]
@MartinPankraz  Done.

**Pull request merged**
